### ISSUE TITLE
doc tags ignored if they appear immediately after @example

### ISSUE THREAD

**Issue by eladb** [aws/jsii#1018]
## :bug: Bug Report

The .jsii manifest doesn't include doc tags if they appear immediately after `@example`.

Repro:

```ts
/**
 * @example foo
 * @boom tag
 */
export class Foo {
}
```

The `.jsii` manifest for `Foo` should include  the `@boom` doctag but it doesn't.

### Affected Languages

- [x] `TypeScript` or `Javascript`
- [x] `Python`
- [x] `Java`
- [x] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:**  0.20.7

**Comment by rix0rrr** [comment]
Yep, known limitation of the TypeScript JSDoc parser.

The following:

```
/**
 * A function
 * @example
 * const x = require('@aws-cdk/aws-x');
 * frob(new x.Thing());
 */
```

Would be parsed as:

```
"@example" => "const x = reuqire('"
"@aws" => "-cdk/aws-x'); frob(new x.Thing());"
```

I can try and see whether the `\n` is maintained, that'll help parsing.

**Comment by eladb** [comment]
This used to work in the past so I guess something changed in how the docparser is used.

**Comment by rix0rrr** [comment]
Correct.

> So in order to properly detect the WHOLE example, I've had to absorb non-standard `@tags` into the @example itself.

**Comment by rix0rrr** [comment]
Something we COULD do is tokenization, and absorb @-signs encountered within quotes, and treat @-signs encountered outside quotes as the start of a new tag.

Would solve most of our existing examples needs (would NOT solve the email-address-like counterexample I showed before).

But it seemed more complex than dictating that examples need to come last.

There is no way to error, because I can't tell whether the `@domain` is legitimately part of the example, or the start of a new tag that shouldn't have been there. If I could do that, I wouldn't need too error, because I could just parse it correctly.
