### ISSUE TITLE
Standardize package configuration

### ISSUE THREAD

**Issue by RomainMuller** [aws/jsii#1075]
Need to introduce a mechanism like `pkglint` on `aws-cdk` that will enforce certain configuration standards across all modules in the mono-repository, so that for example no new module can be introduced without proper listing configuration, as was discovered via #1074.

**Comment by eladb** [comment]
I really think a tool for defining "meta package.json"s can be a very powerful and useful thing. Let's build something like  and use it here and in CDK. Basically the opposite of pkglint - instead of linting a bunch of manually written package.json files, let's just generate them through abstractions (sounds familiar?)
