### ISSUE TITLE
Dependency on org.jetbrains.annotations is incompatible with latest Kotlin stdlib

### ISSUE THREAD

**Issue by eladb** [aws/jsii#1270]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [x] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 0.22

### What is the problem?

In https://github.com/aws/jsii/pull/1234 we added a dependency between jsii Java modules and  [org.jetbrains.annotations@^18.0.0](https://mvnrepository.com/artifact/org.jetbrains/annotations).

However, the latest [Kotlin Standard Library](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/1.3.61) depends on ^13.0.0, which means that Kotlin users will not be able to use jsii java modules without having to resolve conflicts.

**Comment by eladb** [comment]
@RomainMuller I as also wondering, it seems like the jsii-java-runtime still depends on the javax annotations. Is that intentional?

**Comment by RomainMuller** [comment]
The extraneous dependency on JSR-305 is being dropped as part of #1263. A dependency remains on `javax.annotations` so that `@javax.annotations.Generated` is available also for people compiling/using with JDK >= 9 (where the annotation was renamed to `@javax.annotations.processing.Generated` -- and that dependency is the recommended way to deal with this problem).

#1263 also changes the minimum bound for the JetBrains annotations package so it starts at 13.0.0, and hence becomes compatible with the Kotlin STL (the dependency Kotlin STL on JetBrains annotations is a soft requirement - another version can be used if specified somewhere else on the tree).
