### ISSUE TITLE
Expected behavior for * dependencies when compiling into Java

### ISSUE THREAD

**Issue by campionfellin** [aws/jsii#1678]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [x] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.1
* **Platform:**  macOS Catalina

### The Question

What is the expected behavior when compiling `*` dependencies into Java? Here's part of an example `package.json`:

```
 jsii: {
      outdir: "dist",
      targets: {
        java: {
          package: "main",
          maven: {
            groupId: "main",
            artifactId: "main"
          }
        }
      }
    },    
    dependencies: {
      "constructs": "*",
      "cdk8s": "*",
    },
```

This leads to my dependencies in `pom.xml` looking like:

```
  <dependency>
      <groupId>org.cdk8s</groupId>
      <artifactId>cdk8s</artifactId>
      <version>[undefined]</version>
    </dependency>
    <dependency>
      <groupId>software.constructs</groupId>
      <artifactId>constructs</artifactId>
      <version>[undefined]</version>
    </dependency>
```

Changing versions from `*` to a numbered version like `2.0.1` or `0.21.0` seems to fix the issue.

Is this expected?
Any solutions besides explicitly adding the version?

**Comment by RomainMuller** [comment]
How'd you model such a dependency in `pom.xml`?

The reason I as is because I see two ways of addressing this:
1. Generate a valid pom.xml from this configuration (probably also for other languages)
2. Prohibit `*` dependencies

I'd instinctively lean towards option 2, however I also don't like being more restrictive than needed (so if I can express `*` in other languages, I don't see why I'd refrain from doing it).

Generally speaking however, `jsii` packages are expected to adhere to semantic versioning, and having a `*` dependency would mean you're accepting any major version (including incompatible ones) - that doesn't sound like something you'd want to be doing?

**Comment by campionfellin** [comment]
I think for (1), something like this could be acceptable for maven/Java at least:

```
    <dependency>
      <groupId>org.cdk8s</groupId>
      <artifactId>cdk8s</artifactId>
      <version>(0.0.0,]</version>
    </dependency>
```

(2) is also fine with me, if it can be added to the documentation somewhere!

**Comment by campionfellin** [comment]
@RomainMuller either option is fine with me, but I'd prefer (1). I can work on this if you'd like

**Comment by RomainMuller** [comment]
I'm happy with option (1), however as I mentioned on the PR (thanks for that by the way), I feel `0.0.0` should be **included**.

**Comment by SomayaB** [comment]
Closing this issue since it seems to have been resolved. Feel free to reopen.
