### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by SoManyHs** [aws/jsii#1733]
Would it be possible to change the name of the default branch in this repo from "master" to "mainline" or some other alternative? This is already a convention at Amazon internally, and would be compliant with the recommendation by the IETF: https://tools.ietf.org/id/draft-knodel-terminology-00.html

Thanks!

**Comment by SomayaB** [comment]
https://github.com/aws/aws-cdk/issues/8485

**Comment by RomainMuller** [comment]
I personally very much dislike `mainline` and would be much more favorable to `main`. We've been asking our open source support team whether they have any recommendation or standard with respects to the new branch name.

In any case, we are looking into this, but it might take a little while because of the implications (our CI/CD infrastructure is tied to a particular branch name, and changing that will require treading carefully; so we need to plan our way first 😅).
