### ISSUE TITLE
Consider if we want to automatically run tslint as part of jsii

### ISSUE THREAD

**Issue by eladb** [aws/jsii#2]
To keep a high bar on code quality (at least for constructs we publish)

**Comment by eladb** [comment]
Why close? I think this is definitely worth a discussion. Could be a nice feature to add?

**Comment by RomainMuller** [comment]
I closed because `tslint` is going away, and being replaced with `eslint`.
I'm afraid this imposes a lot of opinion which isn't *necessary* for correctness.

Also - `jsii` level support for this would be mandated by a general interest; not just to serve CDK.
I can't help but feel that you'd get more flexibility configuring a linter in "user land" instead of having JSII force one on you.

**Comment by RomainMuller** [comment]
I'll close it because I don't think doing this "directly in `jsii`" is not something that'll happen anytime soon. And listing is just too subject to controversy (i.e: personal taste).
