### ISSUE TITLE
can a diamond dependency be used

### ISSUE THREAD

**Issue by shivlaks** [aws/jsii#2256]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [x] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.14.1 
* **Platform:** macOS Catalina (10.15.7)

### The Question

Is it possible to use a diamond dependency if there are no conflicting (potentially duplicated) properties?
A recent [CDK PR](https://github.com/aws/aws-cdk/pull/10356) motivated this question where a construct was updated to declare interfaces in the following manner:
![image](https://user-images.githubusercontent.com/32604953/99365422-1e9b3800-286c-11eb-947a-adac2d62d3f7.png)

a simplified view of the interface declarations here looks like the following:

```ts
interface CommonStartBuildOptions {
  readonly buildSpec?: BuildSpec;
  readonly encryptionKey?: kms.IKey;
  readonly cache?: Cache;
  readonly environment?: BuildEnvironment;
  readonly role?: iam.IRole;
  /**
   * The number of minutes after which AWS CodeBuild stops the build if it's
   * not complete. For valid values, see the timeoutInMinutes field in the AWS
   * CodeBuild User Guide.
   *
   * @default Duration.hours(1)
   */
  readonly timeout?: Duration;
  readonly environmentVariables?: { [name: string]: BuildEnvironmentVariable };
}

export interface StartBuildOptions extends CommonStartBuildOptions {
  readonly source?: ISource;
  readonly artifacts?: IArtifacts;
  readonly secondarySources?: ISource[];
  readonly secondaryArtifacts?: IArtifacts[];
}

export interface CommonProjectProps extends CommonStartBuildOptions {
  readonly description?: string;
  readonly badge?: boolean;
  readonly projectName?: string;
  readonly vpc?: ec2.IVpc;
  readonly subnetSelection?: ec2.SubnetSelection;
  readonly securityGroups?: ec2.ISecurityGroup[];
  readonly allowAllOutbound?: boolean;
  readonly fileSystemLocations?: IFileSystemLocation[];
  readonly grantReportGroupPermissions?: boolean;
}

export interface ProjectProps extends StartBuildOptions, CommonProjectProps {
}
```

However there was a failure with the java code generation:

>  [ERROR] /tmp/npm-packf10vHL/monocdk/src/main/java/software/amazon/awscdk/services/codebuild/ProjectProps.java:[10,8] interface software.amazon.awscdk.services.codebuild.ProjectProps inherits unrelated defaults for getTimeout() from types software.amazon.awscdk.services.codebuild.StartBuildOptions and software.amazon.awscdk.services.codebuild.CommonProjectProps

Is this something that we could support? If not, perhaps it's an opportunity to validate

**Comment by MrArnoldPalmer** [comment]
Related to this is when a TS interface or class implements two interfaces that share a property/method with the same name and type. This will generate Java interfaces with default implementations for both and the compiler doesn't know which one to use. Re-declaring the implementation at the implementer level when there is a conflict will fix this. We saw this in https://github.com/aws/aws-cdk/pull/12700.

**Comment by RomainMuller** [comment]
Turns out the code is generated correctly for diamond dependencies, however what happens and probably cannot be supported in a safe way is when two upstream interfaces declare optional properties by the same name (and type, but this is already checked for).

This can _appear_ to happen with a diamond graph, if the interface that declares some optional property (and is inherited by a single child through multiple parents) is not exported... in such cases declarations are "promoted" to the extending classes as the internal interface is erased from the exported model.

In any case - even though we _could_ generate code that compiles, given a snapshot of a dependency graph, this cannot be made to be forward-compatible with addition of new a conflicting declaration in an extended dependency: the solution would be to "override" the `default` implementation if there are > 1 parents declaring it; but we cannot know what will happen in the future. Additionally, this scenario would likely result in usability issues.
