### ISSUE TITLE
Unknown error: Cannot read property 'declarations' of undefined

### ISSUE THREAD

**Issue by eladb** [aws/jsii#2349]
### Affected Languages

- [x] `TypeScript` or `Javascript`
### General Information
* **JSII Version:** 1.15.0 (build 585166b), typescript 3.9.7
* **Platform:**     Darwin

### What is the problem?

I am not 100% sure about the circumstances of this error, but the compiler throws this error (usually when there are actual compilation issues).

### Verbose Log

```
error JSII9997: Unknown error: Cannot read property 'declarations' of undefined -- TypeError: Cannot read property 'declarations' of undefined
    at Assembler._validateHeritageClauses (/Users/benisrae/code/cdk/aws-cdk/node_modules/jsii/lib/assembler.js:664:51)
    at Assembler._visitNode (/Users/benisrae/code/cdk/aws-cdk/node_modules/jsii/lib/assembler.js:581:18)
    at Assembler.emit (/Users/benisrae/code/cdk/aws-cdk/node_modules/jsii/lib/assembler.js:101:45)
    at async Compiler._consumeProgram (/Users/benisrae/code/cdk/aws-cdk/node_modules/jsii/lib/compiler.js:149:30)
    at async /Users/benisrae/code/cdk/aws-cdk/node_modules/jsii/bin/jsii.js:72:39
```

### Repro

I've uploaded a zip file with the repo to [here]. To see the issue, run `yarn build` from `packages/@aws-cdk/aws-secretsmanager`.

[here]: https://amazon.awsapps.com/workdocs-beta/index.html#/document/117d35d722ba1d752c4ce95faae570c8b5078ff6277aaa0a62c67ef9d263b725

**Comment by RomainMuller** [comment]
I see - the code does not compile, so I think what is happening is the type checker inserts an "error type" which does not have an associated symbol (intentionally); which then causes this check to fail.

In such cases, we cannot rescue the failure anyway, and double-reporting it is no use... So I'll just make that code more defensive to the missing symbol.

It's also fairly tricky to reproduce because this will mostly materialise when working under `--watch` mode... So the type checker has a previous "good" type system to use as a crutch (so it knows where to insert what kind of "error type" as a placeholder, when things "temporarily" break)... Reproducing it (for testing purposes) is tricky because we would then need to reproduce the journey that led the compiler in that state... I will not attempt going down that road.
