### ISSUE TITLE
Support codeOnly for Go in jsii-pacmak

### ISSUE THREAD

**Issue by ansgarm** [aws/jsii#2848]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [x] `Go`

### General Information
* **JSII Version:** 1.29.0
* **Platform:**     

* [ ] I may be able to implement this feature request

* [ ] This feature might incur a breaking change

### Description

Currently `jsii-pacmak` seems to create a `go.mod` file even if `--code-only` is supplied.
Is there a reason for that?

### Proposed Solution

Don't generate / include a `go.mod` in the output directory if `codeOnly: true` / `--code-only` is set for `jsii-pacmak`.

**Comment by MrArnoldPalmer** [comment]
So `--code-only` doesn't mean to only generate source files, it means to not to `build` the package. In java, when you run `--code-only`, `pom.xml` is still generated with a list of dependencies, we just don't run `mvn build` and create a `.jar` file.

With Go, since the source code is the package artifact, the only difference with `--code-only` is that we don't create `local.go.mod` and run `go build` against that to verify that compilation occurs.

This is expected behavior. Can I ask what the use case is that you don't want to create `go.mod`?

**Comment by ansgarm** [comment]
Ah, thank you for the clarification, @MrArnoldPalmer 👍 

The background is `jsii-srcmak`, where we decided to [integrate just the Go code](https://github.com/cdklabs/jsii-srcmak/pull/476#issuecomment-844757328) into the Go project of a user.
Currently the `go.mod` is [simply deleted](https://github.com/cdklabs/jsii-srcmak/blob/f547ab2f882542ebd42ccc41695befdbd583d8c1/src/srcmak.ts#L62) after copying everything and I just thought we could get rid of that step. But I just misunderstood that flag, so nevermind 😅

Going to close this. Have a nice weekend 👋
