### ISSUE TITLE
Does java for jsii is still working fine or it only can be generate but cannot be used?

### ISSUE THREAD

**Issue by jianweic** [aws/jsii#2971]
## :bug: Bug Report
-->
- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ /] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

I put detail on
https://github.com/aws/jsii/issues/2966#issue-976365495

**Comment by NGL321** [comment]
Hey @jianweic,

Sorry for the delayed response here. You can usually determine whether a version of JSII is broken for a language by checking the corollary CDK library. Since we release CDK for each language in parallel, if a single language is broken, the JSII version will roll back.

All that to say, JSII Java generation is working fine!

😸 😷
