### ISSUE TITLE
feat(go) - research using generics for improved UX

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#3276]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [x] `Go`

### General Information
* **JSII Version:** 1.49.0
* **Platform:** *    

* [x] This feature might incur a breaking change

### Description
Go 1.18 is scheduled to release as stable in Feb 2022 with support for generic types. This new feature allows us to potentially take an alternative approach to supporting [`optional values`](https://github.com/aws/aws-cdk-rfcs/blob/master/text/204-golang-bindings.md#optional-values-and-pointer-types), enabling [type casting](https://github.com/aws/jsii/issues/2819), and various runtime improvements.

#### Optional Types
Definition of some wrapper type like:
```go
type Optional[T any] struct{
	val T
	defined bool
}
```
Would allow code generating `Optional[Type]` instead of `*Type` everywhere. This largely would have similar semantics to the user as all types, regardless of whether they are optional or required in typescript, would have to be this wrapper type in order to uphold backwards compatibility guarantees as detailed in the RFC. It may however emerge as the more idiomatic solution once generics are commonly used in Go, and they can be defined inline instead of using a utility function like `jsii.String` or needing to allocate a variable previously.

Additionally this could simplify reflection code within the Go runtime where currently some relatively complicated logic exists around inspecting and dereferencing pointers during reflection.

#### Type Casting

We may be able to define a function, returning a generic type representing a parent or child class (in typescript) to support [downcasting as needed for escape hatches](https://github.com/aws/jsii/issues/2819).

#### Runtime Improvements

Changing JSII runtime functionality to use generics:
```go
// from
func (c *Client) Get(props GetProps) (response GetResponse, err error)
// to
func (c *Client) Get[A any](props GetProps) (response GetResponse, err error, val A)
```
Could potentially give stronger compile time guarantees for the runtime library and generated code and reduce the usage of unsafe pointer manipulation.

**Comment by RomainMuller** [comment]
I extensively prototyped in the https://github.com/aws/jsii/tree/rmuller/explore/go1.18-generics branch.

Here are some of the high-level findings (pending a more comprehensive writeup):
- Methods cannot introduce new type arguments (they may of course use the type parameters of the type they are a member of)
- We can design a "marker" interface that can be used in any place where a value is optional (`nil`-able)
  ```go
  type Option[T any] interface {
	// This is merely a marker function to facilitate
    // getting the underlying value type through reflection
    Unwrap__() T
  }
  ```
  - All generated types simply implement this interface (`T` is the implementing type)
  	- This means a signature that accepts any `T` can be updated to accept `Optional[T]` without breaking
  	- Unfortunately any given type can only implement the marker ONCE (as it'd otherwise require multiple identically-named methods to be implemented, which is impossible)
  - Structs (in the `jsii` sense) and enums are passed by-value when required, so they simply cannot be `nil`.
  - We still need to use wrappers for primitive types (`string`, `float64`, etc...), but instead of being pointers to these types, they can be "real" aliases
    ```go
    type String string
    // String is a valid value for Option[String]
    func (s String) Unwrap__() String { return s }
    ```
  	- These cannot be `nil` when required.
  	- They implement `Option[T]`
  	- These types have perhaps a more "go native" feel to them.
  - The marker allows runtime validation that structs have values for all required (and `nil`-able) fields they have
- We can streamline the runtime APIs that currently accept `reflect.Type` so they are instead generic functions
  ```go
  // Before
  RegisterStruct(reflect.TypeOf((*StructType)(nil).Elem())

  // After:
  RegisterStruct[StructType]()
  ```
- We can implement a decent `UnsafeCast` feature using generics, where the experience could look like so:
  ```go
  original := SomeFunction() // A union of structs
  downCasted := jsii.UnsafeCast[SpecificStruct](original)
  ```

**Comment by MrArnoldPalmer** [comment]
These definitely look like some significant improvements that at first glance appear to make the Go experience easier to get started with and understand. We should work towards providing a working experience for users to try and provide feedback on though if possible without rewriting too much of our current implementation, if only to provide further validation without committing to an entirely new approach.

**Comment by RomainMuller** [comment]
Additional notes in https://github.com/aws/aws-cdk-rfcs/pull/397
