### ISSUE TITLE
[Java] Interface implementations aren't annotated

### ISSUE THREAD

**Issue by RomainMuller** [aws/jsii#333]
The generated implementations for interface types are not annotated with the JSII annotations, resulting in their being handled as `Object` though the language boundary. This de-facto opts them out of type model validation that could catch issues like the one reported in awslabs/aws-cdk#1347

**Comment by rix0rrr** [comment]
I believe this ticket is saying that proxy classes are generated like this:

```java
    @software.amazon.jsii.Stability(software.amazon.jsii.Stability.Level.Stable)
    final class Jsii$Proxy extends software.amazon.jsii.JsiiObject implements S3ArtifactsProps {
```

As opposed to for example Python where it's generated like this:

```python
@jsii.data_type(jsii_type="@aws-cdk/aws-codebuild.S3ArtifactsProps", jsii_struct_bases=[ArtifactsProps], name_mapping={'identifier': 'identifier', 'bucket': 'bucket', 'name': 'name', 'encryption': 'encryption', 'include_build_id': 'includeBuildId', 'package_zip': 'packageZip', 'path': 'path'})
class S3ArtifactsProps(ArtifactsProps):
```

The difference being the annotation that the object would serialize to a `@aws-cdk/aws-codebuild.S3ArtifactsProps` struct It is present on classes:

```java
@software.amazon.jsii.Jsii(module = software.amazon.awscdk.services.codebuild.$Module.class, fqn = "@aws-cdk/aws-codebuild.CfnProject")
public class CfnProject extends software.amazon.awscdk.core.CfnResource {
```

However, I don't have enough state to judge the merit or applicability of this issue.

* Maybe adding the annotation is enough, maybe it isn't?
* I don't know whether Romain was thinking the validation would be done on the jsii kernel side, or on the Java jsii runtime side (in the latter case, adding the attribute is not enough, and more validation should be added instead).
* Maybe because the kernel is doing [some validation on required properties already](https://github.com/aws/jsii/blob/master/packages/jsii-kernel/lib/serialization.ts#L324) (added since this issue was filed), this is no longer applicable?
* One would assume that since Java is statically typed, such runtime checking should not even be necessary (epsilon bugs in the runtime, which the linked issue was an instance of).

I would recommend waiting until @RomainMuller gets back and asking him whether he thinks this issue should still be solved.

**Comment by RomainMuller** [comment]
This is in fact no longer an issue, as Java started to pass `struct`s by value instead of by reference.
