### ISSUE TITLE
Rosetta: Incorrect transliteration for namespace/submodule usage in Go

### ISSUE THREAD

**Issue by jsteinich** [aws/jsii#3551]
### Describe the bug

Translating a reference to a namespaced resource results in `#error#` being output in the resulting Go code.

### Expected Behavior

The namespace should be maintained or separate import statements should be generated.

### Current Behavior

The namespace is lost and `#error#` is generated instead.

### Reproduction Steps

```typescript
import * as aws from "./.gen/providers/aws";
const awsKmsKeyExamplekms = new aws.kms.KmsKey(this, "examplekms", {
  deletionWindowInDays: 7,
  description: "KMS key 1",
});
```

results in 

```go
import aws "github.com/aws-samples/dummy/genprovidersaws"
awsKmsKeyExamplekms := #error#.NewKmsKey(this, jsii.String("examplekms"), map[string]interface{}{
	"deletionWindowInDays": jsii.Number(7),
	"description": jsii.String("KMS key 1"),
})
```

### Possible Solution

https://github.com/aws/jsii/pull/3508 tackled a similar issue, so there maybe a similar solution available; however, I haven't checked the code.

### Additional Information/Context

This came up while working on https://github.com/hashicorp/terraform-cdk/pull/1782.
There is a snapshot test that illustrates the issue.

### SDK version used

1.55.1, also observed in 1.58.0

### Environment details (OS name and version, etc.)

docker.mirror.hashicorp.services/hashicorp/jsii-terraform (based on jsii/superchain)

**Comment by RomainMuller** [comment]
That's a tricky one... the issue here is that the original TypeScript traverses a namespace boundary here (`aws.kms.KmsKey` goes from the `aws` namespace into the `kms` namespace to get `KmsKey`), which in Go should translate to _another_ import being generated (`github.com/aws-samples/dummy/genprovidersaws/kms`).

This is actually quite different from #3508 in the sense that we need to modify the list of go packages to import here, but we only "discover" this information after it's too late (we already emitted imports at that stage).

In order to address this, we'd need to either:
- Change how the code is emitted so we can alter the imports list throughout code generation, and emit it last
- Pre-process the AST to discover all nested namespaces we need to import at the very beginning

**Comment by RomainMuller** [comment]
I'm exploring a possible solution. I expect it'll take me probably a few days to get through this (unless I discover I am overthinking it).
