### ISSUE TITLE
Expectation of error handling for language bindings

### ISSUE THREAD

**Issue by jasdel** [aws/jsii#369]
JSII does not provide a way for language bindings to know which methods and property can throw errors. JSII does not distinguish between JSII run time errors (e.g. unable to load module) and errors thrown by the JavaScript code running. Mixing these two classes of errors without providing a way to distinguish them prevents language bindings from generating idiomatic language code for languages without support for exceptions.

If JSII had a way label a method or property as throwing a class of error language binding could generate friendly language code reflecting the error to the user. 

For a concrete example with the CDK and JSII Go language bindings, `cdk.App` has a method called `Run`. This method seems like a natural location errors would be returned. If JSII error modeling was available, `Run` could be updated to state it throws an exception. In go this would be be generated as returning a `error`.

```go
app := cdk.NewApp()

//...

if err := app.Run(); err != nil {
    // handle error.
}
```

In addition, to being able to generate language bindings aware of errors, JSII being able to model error classes allow users of the JSII language bindings to inspect the returned error to extract structured values from the returned error.

Related to #50

**Comment by eladb** [comment]
We should definitely formalize this at the spec level, but for the immediate term, all errors thrown by CDK code (the primary user of Jsii) are unrecoverable by design (in fact, trying to recover from exceptions will likely result in a corrupted tree), and therefore lend themselves well to Go panics. 

This is somewhat true for JavaScript in general, especially when it comes to tools (which is the domain Jsii is designed to support). Unlike java, JavaScript’s recoverable errors are usually signaled through the API and not through exceptions, very similar to how Go models exceptions through return values. When/if we find a need to define a general pattern for recoverable errors in Jsii, language bindings like Go could benefit from it and generate idiomatic error results. For CDK, this is not needed at the moment.
