### ISSUE TITLE
Python aws-cdk-lib: Invalid escape characters

### ISSUE THREAD

**Issue by DFEvans** [aws/jsii#4532]
### Describe the bug

In the Python bindings, the docstring on `aws_cdk.aws_secretsmanager.__init__` contains the text:

```[...] If none are defined then the following set is used: `% +~`#$&*()|[]{}:;<>?!'/@"\`.```

At the end of this line, the backslash-backtick sequence is interpreted by Python as an invalid escape character.

### Expected Behavior

The code does not contain invalid escape sequences.

### Current Behavior

The code contains an invalid escape sequence, which causes a warning. This is raising a SyntaxError for a specific Python install we have (3.10.9, potentially a vendorised version - proving difficult to track down exactly why only one install is causing trouble!).

### Reproduction Steps

Import CDK in Python - check for warnings or errors related to escape sequences.

### Possible Solution

It appears the docstring is taken from the Markdown at:

https://github.com/aws/aws-cdk/blob/52edf299a42f17254da0151bb939bcb303d0e5e6/packages/%40aws-cdk/aws-secretsmanager/README.md

In Python alone, replacing `\` with `\\` would be the fix, but a multi-language solution is presumably more complex!

### CDK CLI Version

2.68.0 (build 25fda51)

### Node.js Version

v18.9.0

### OS

Ubuntu

### Language

Python

**Comment by kaizencc** [comment]
this is a tough one. it's not as simple as treating the entire string as a raw string in jsii (i.e. `r'''`) because there are characters we'd like to escape, like `\n`. Simply changing the 2 instances where this is happening would be the path of least resistance but would not address the actual problem and open us to the same issue in the future. still looking into this one, but i don't have a magic solution yet.

**Comment by davletovalmir** [comment]
@bruceduhamel if you wondered ever since why `poetry` would through `SyntaxWarning`s and `pip` would not - it's because `poetry` doesn't generate pre-compiled python files (`**/__pycache__/*.pyc`) on package installation, while `pip` does. And since all your packages are **parsed** and interpreted at runtime, they throw `SyntaxWarning`, while pre-compiled files are basically byte-code that are **already parsed** and are subject to execute only. Hope that helps!

I spent a whole day figuring this out and this issue was my only clue that I'm not alone with this.
