### ISSUE TITLE
Improve stack traces across language boundaries

### ISSUE THREAD

**Issue by RomainMuller** [aws/jsii#47]
When making a cross-language call that ends up throwing an exception, the stack trace only contains the NodeJS section, and not the host application section. The same applies when a stack trace is internally gathered (for example, to track construct creation locations).

The runtime needs to pass a list of stack frames to the kernel so the exception stack trace can be enhanced to include all relevant information. The kernel then will need to somehow make this external trace a part of the regular trace, so that no special handling is required at stack trace collecting sites.

This could be done by runtime-generating one or more methods, just for the sake of adding stack frames in the Node process. It may also be possible to leverage the fact that almost any string can be a valid method name (so as to only use one stack frame instead of several).

**Comment by rix0rrr** [comment]
## When calling frontend language -> TypeScript

There are two stack traces:
* One inside the node process (all the way from reading the jsii request to where the error occurred)
* One inside the frontend language process (from the users code to parsing the error response from jsii and throwing)

Both of these contain extraneous details that might be useful in case of jsii errors, but in normal operation only serve to confuse the user. We should probably cut those down to the relevant pieces (involving user written code).

----

## When calling frontend language -> TypeScript -> frontend language (callbacks)

The stack trace produced by the frontend language callback is thrown on the ground, and the NodeJS stack trace shows some more useless lines where the jsii kernel is "calling into" the frontend language.

Again, we should probably clean up the stack traces, *and* we should definitely be transporting and extending stack traces both ways, so that the ultimate stack trace and error represent the whole call path up to the final error.

**Comment by corymhall** [comment]
I think this should be re-opened. This is still needed for things like the CDK validator plugins.
