### ISSUE TITLE
Java JSII runtime dependency on Jackson is at risk when version 3.0.0 gets realeased

### ISSUE THREAD

**Issue by skinny85** [aws/jsii#602]
Right now, the [Java JSII runtime](https://mvnrepository.com/artifact/software.amazon.jsii/jsii-runtime/0.14.0) depends on [`jackson-core`](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core) and [`jackson-databind`](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind) are right now modeled as `[2.9.8, )`. Which means the moment version `3.0.0` of Jackson is released, we have a very real risk of breaking builds for every Java customer (a method we call on `ObjectMapper` in `JsiiObjectMapper`, for example, has been removed from master already).

We should think about how to mitigate this risk.

**Comment by RomainMuller** [comment]
I propose (in #629) to make the version range stricter and not allow nee major versions to sneak in. Pinning to the particular version number feels unsafe due to our current inability to be automatically notified about security issues found in our dependencies, and promptly reacting to those.

If/when we can make @dependabot cater for those, we might be able to get back to a single version number style "safely".

**Comment by lealceldeiro** [comment]
How do you plan to mitigate the risks introduced by vulnerabilities in older versions of the jackson library (currently used in the project).
Example: There's a dependency to [com.fasterxml.jackson.core](https://mvnrepository.com/artifact/com.fasterxml.jackson.core) » [jackson-databind](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind) `[2.11.3,2.12-a0)`, which contains a Direct vulnerability: [CVE-2020-36518](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518)
