### ISSUE TITLE
.NET Generator/Runtime: primitive types should all be nullables in props object

### ISSUE THREAD

**Issue by assyadh** [aws/jsii#715]
The reasoning is that in the case of primitives, there is no way to tell if a required primitive was actually set by the customer (ex: a required int will default to 0).

If we set it to int? then the customer has to set a value, and we can then check for the absence of null values in the runtime.

**Comment by MrArnoldPalmer** [comment]
This definitely warrants more discussion as well as some experimentation on our part.

For the purpose of my own understanding, let me restate.

When defining an interface/class/whatever in DotNet, and it has a required primitive type property which is not set by the user during construction, the value will default to whatever the types default value is? So we can't actually tell if it was passed by the user, or just defaulted?

Right now it seems that the Node process would fail and throw an error because the required property is missing. Obviously it would be ideal to catch this before that. However, making this change would mean that though we could catch this in the DotNet runtime, it still would not be detectable at compile time.

Does that seem correct to you @assyadh ?
