### ISSUE TITLE
How does jsii work?

### ISSUE THREAD

**Issue by wcauchois** [aws/jsii#737]
Hi,

I found JSII while diving into CDK internals to figure out how it works. However, in the README.md I can't even find a basic explanation of the method by which it operates. Looking at GH issues, it seems maybe there's some sidekick node.js process that JSII then communicates with? The README is quite generic, and even a few sentences about the mode of operation would be very interesting and much appreciated.

Apologies if this is a spurious issue or something that is known, but I thought I'd lend my two cents as someone who stumbled upon this project and is interested in knowing how it works.

**Comment by RomainMuller** [comment]
Hey @wcauchois,

The issue isn't *spurious* in any way, it demonstrates there is interest in this information and helps us prioritize where we spend effort - so thank you for filing it in.

There used to be some basic explanation of how `jsii` achieves it's magic, but I have prune it for it was alluding to too many outdated details. I definitely plan on re-introducing documentation about that sooner rather than later.

To answer your question superficially (as I'm not going to be able to restore that documentation right away I'm afraid 😆):
1. The `jsii` compiler is effectively a *modified* TypeScript compiler that'll output a `.jsii` Assembly file, that describes the exposed API of the module (it includes all types exported from the file pointed to by the `types` key in the `package.json` configuration).
2. Then, `jsii-pacmak` generates code in **Python**, **C#**, **Java** (and more to come) that models the same API as the TypeScript.
   * The generated code *bundles* the **Javascript** code that was the result of compiling the 
**TypeScript**
   * At run-time, a `node` process is spun up and the generated classes interact with this process through JSON IPC over STDIN/OUT pipes.
