### ISSUE TITLE
Can't use Lazy.stringValue from Python

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#807]
## :bug: Bug Report

The following seems like it should work: 

```python
import jsii
from aws_cdk import core


class TestpythonStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # The code that defines your stack goes here
        lazy = core.Lazy.string_value(Producert())

        core.CfnOutput(self, 'Output', value=lazy)


@jsii.implements(core.IStringProducer)
class Producert:
    def produce(self, context):
        return 'whee'
```

But in fact this leads the runtime to trying to serialize a FUNCTION back to jsii:

```
[jsii-kernel] fromSandbox registerPostProcessor(pp) { postProcessor = pp; } [{"serializationClass":"Any","typeRef":{"type":{"primitive":"any"}}}]
```

Which fails (obviously).

**Comment by rix0rrr** [comment]
This is where the function is coming from: 

https://github.com/aws/aws-cdk/blob/9a1fdf7551d0a711bfe187bfa0e3118f80fdfd4a/packages/%40aws-cdk/core/lib/private/resolve.ts#L48

**Comment by rix0rrr** [comment]
Current theory: anonymous implementation of interfaces never works.

(Which is an issue, since we use that in a couple of places)

**Comment by RomainMuller** [comment]
So it turns out that the following will be sent to Javascript as an `Object` reference with blind (aka accepting `any` parameters, returning `any`) overrides:

```py
@jsii.implements(core.IStringProducer)
class Producert:
    def produce(self, context):
        return 'whee'
```

As it turns out, this comes from the fact the Python runtime does not consider interfaces at all when sending references to Javascript... It only cares about a `jsii` base class (this class has none, hence goes to `Object`), and as there *could* be multiple interfaces, it does not consider naming the reference after those at all.

## Quick Fix Option

As a quick fix, we could leverage the fact that there is *exactly* one interface in this case, and use that to name the reference. The `create` call for the `Producert` instance ends up in the `else` branch at line `:129`. It could check the value of `d.__jsii_ifaces__` and if there is *exactly one* value in there, it could use that as the `d.__jsii_type__` value.

https://github.com/aws/jsii/blob/0239b91dddcd797cdadae3f8cfbdf793c157e9dc/packages/jsii-python-runtime/src/jsii/_kernel/__init__.py#L109-L133

## Full Solution

In order to fully solve this problem, the Kernel needs to allow `create` to specify a list of implemented interfaces, so the runtimes can effectively `create Object implementing IFoo, IBar`, which would allow callback registration to look up the actual type information for the implemented members. This is currently a missing feature in the Kernel.

**Comment by rix0rrr** [comment]
I believe this has been fixed in the latest release.

**Comment by serverlessunicorn** [comment]
Possible this has resurfaced? I'm using CDK v 1.49.1 (build 7d6321f) and I can't create Lazy's in Python 3.8 without getting the dreaded "...not no attribute '__jsii_type__'" error message.
